### ISSUE TITLE
Color Inventory somehow not linked to colors

### ISSUE THREAD

**Issue by yannicgraeser** [getflourish/Sketch-Style-Inventory#42]
As you can see I created a color inventory and I defined swatches.

But my problem is that the defined colors do not count how often I used the color.
I seems like the defined colors and the colors I use on my artboards are not linked at all.

I am using OS 10.10.2 and Sketch 3.2.2.

I don't know if it's a but or if I am making a mistake.
Looking forward to hearing from you!

![Screenshot](http://i.imgur.com/VQFDDsU.png)

**Comment by getflourish** [comment]
There must have been a change to the API where I was counting colors based on hexValue. Using the Color object itself now. Fixed.
