### ISSUE TITLE
3.3 crashes

### ISSUE THREAD

**Issue by PMDavies** [getflourish/Sketch-Style-Inventory#43]
Consistently getting errors on Sketch 3.3 with the plug-in. Generating colour inventory creates a blank artboard; other selections stall the app with a constant spinning wheel.

**Comment by getflourish** [comment]
Thanks for reporting. Will look into it and port it to the new plugin format.

**Comment by sophiamf** [comment]
Does anyone know why inventory doesn't work (at all, generates blank art board) with 3.3?

I'm also having an issue where color swatch RGB/HEX values are completely different between computers. Likely a global setting but any feedback would be very much appreciated.

**Comment by getflourish** [comment]
I’m looking into this right now. API changes.

**Comment by gordonirving** [comment]
Same here: both Inventory commands create an empty artboard with a blank square inside, Merge and Define Swatches do nothing and Generate hangs the app.

**Comment by getflourish** [comment]
It’s pretty crazy in 3.3. Hope to get it fixed by tonight. Thanks for reporting!

**Comment by getflourish** [comment]
Fixed the crashes. Actually, in 3.3 the plugin should be more stable even with complex files. Still need to fix the "center view". Waiting on feedback from Bohemian Coding.

**Comment by sophiamf** [comment]
You guys are the best! Thanks :)

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.1.51&pv=8.2]
On Tue, Apr 14, 2015 at 15:55, Florian Schulz <notifications@github.com> wrote:Fixed the crashes. Actually, in 3.3 the plugin should be more stable even with
complex files. Still need to fix the "center view". Waiting on feedback from
Bohemian Coding.

—
Reply to this email directly or view it on GitHub
[https://github.com/getflourish/Sketch-Style-Inventory/issues/43#issuecomment-93040492] .[https://github.com/notifications/beacon/AKQOWqSbEQdYQ94XIJ4QXiLceO32QvbTks5n_WgUgaJpZM4D_UIJ.gif]
