### ISSUE TITLE
Implement view centering and zooming in 3.3

### ISSUE THREAD

**Issue by getflourish** [getflourish/Sketch-Style-Inventory#44]
Due to API changes, the plugin is unable to correctly focus the view on artboards / layers.

**Comment by frankko** [comment]
Not sure if this helps, but since 3.3 I’ve been doing something like so:

``
var doc = context.document;
var view = [doc currentView];
``

then select either an artboard or a layer, as you would, then

``
[view zoomToSelection];
``

**Comment by getflourish** [comment]
Thanks! :)
