### ISSUE TITLE
how to generate/Text Style Inventory

### ISSUE THREAD

**Issue by alanontheweb** [getflourish/Sketch-Style-Inventory#48]
I want to create the CSS text file, but the keyboard shortcut on the site isn't working and I don't see the option in the menu bar.

https://camo.githubusercontent.com/2bc77ed486c042a0ca5eb33374104c0898d41afb/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3937343737332f5f6b656570616c6976652f5374796c65253230496e76656e746f72792f536b657463682532304353532e676966

What am I doing wrong?

**Comment by pibemillo** [comment]
Same here, running 3.3.3. Anyone figure it out?

**Comment by katmaha** [comment]
I'm running 3.4.3 (trial version), that command does nothing for me. Anyone else?

**Comment by getflourish** [comment]
Will look into it when updating for 3.5

**Comment by getflourish** [comment]
Updated the plugin to the new bundle format. Generate & Export should work again with the latest non-App Store versions.
