### ISSUE TITLE
doesn't generate text styles at all

### ISSUE THREAD

**Issue by szmarci** [getflourish/Sketch-Style-Inventory#49]
If I hit `ctrl + option + cmd + I` and select all the options, I only get the colors generated.
I'm using the latest version of Sketch (Version 3.3.2 (12043))

**Comment by DainaReed** [comment]
I have same problem, did you solve it?

**Comment by getflourish** [comment]
Will look into it when updating for 3.5

**Comment by getflourish** [comment]
Updated the plugin to the new bundle format. Generate & Export should work again with the latest non-App Store versions.
