### ISSUE TITLE
Doesn't generate anything on larger file.

### ISSUE THREAD

**Issue by design2dev** [getflourish/Sketch-Style-Inventory#53]
I tested the plugin on a new sketch file with 1 artboard that has 2 rectangles. It works.
But on my other Sketch file that is 13mb. 

It generates only the "Style Inventory" page and leaves it blank.
screenshot: https://www.dropbox.com/s/lj5tlgcdyncymeb/Screenshot%202015-06-30%2018.55.05.png?dl=0

I have Sketch 3.3 and the latest plugin vrsn. thanks

**Comment by DainaReed** [comment]
I have same problem, did you fix it?

**Comment by janfehlis** [comment]
Same issue here.

**Comment by mel2669** [comment]
Same here. What gives

**Comment by markbreneman** [comment]
Partial Ditto. I have a semi-large Sketch file(over 30 mb) and Generate worked however there were blatant colors that it was missing.  As a partial fix, I moved all my key artboards( about 10 or so of 30ish to another file), and then re-ran the generate command and it got all the colors.

**Comment by ellisneder** [comment]
I followed @markbreneman's lead and copied key pages into a new file and then pieced together a style guide. A few text styles were still missing though. This plugin gets you started but won't generate the complete style guide we all want, so check the results carefully.

**Comment by davidvb** [comment]
Having the same issue with a file of only 1.3MB.  
Using Sketch 3.5.1 Stable.. 

@getflourish Any clue on a timeline for a fix? Would be great!

**Comment by getflourish** [comment]
Updated the plugin to the new bundle format. Generate & Export should work again with the latest non-App Store versions.

**Comment by markbreneman** [comment]
👏👏
