### ISSUE TITLE
Both the text style artboard and symbols artboard size are not correct in Sketch 3.4

### ISSUE THREAD

**Issue by cszwdy** [getflourish/Sketch-Style-Inventory#56]

**Comment by sledneck** [comment]
Don't know if this helps but here's an error log I keep getting.

![screenshot 2015-11-04 17 22 52](https://github-cloud.s3.amazonaws.com/assets%2F5421836%2F10957386%2Fbb592cb4-8318-11e5-8e52-71433de23e4f.png)
![screenshot 2015-11-04 17 23 00](https://github-cloud.s3.amazonaws.com/assets%2F5421836%2F10957385%2Fbb5852f8-8318-11e5-8582-5e0c0d5cacda.png)

**Comment by getflourish** [comment]
Will revise when updating for 3.5
