### ISSUE TITLE
Generate Color Inventory Buggy?

### ISSUE THREAD

**Issue by apertureless** [getflourish/Sketch-Style-Inventory#57]
Hey 
It seems the counting on the color swatches isnt working properly.

**Comment by kennethknudsen** [comment]
My counting is working, but naming is not working? i'm using sketch 3.4.4

**Comment by apertureless** [comment]
:D Naming works for me. You have to select the swatches in your color inventory that you want to name and then unter the plugin menu -> inventory -> define swatches.

**Comment by kennethknudsen** [comment]
I just tried your method without succes. Let's hope the author or a contributor fixes this issue :)

**Comment by apertureless** [comment]
Oh I see, I didn't upgraded to 3.4.4. gonna check it after update.

**Comment by apertureless** [comment]
okay still working with 3.4.4. 

[gif](https://gfycat.com/RemotePoisedAmoeba)

**Comment by kennethknudsen** [comment]
It's working now! Thanks to your gif I now know that i have to select the group and then define the swatch. I tried selecting only the color/shape and then hitting the "define swatch". Works for me now :D Thanks a million!

**Comment by apertureless** [comment]
You're welcome :)
