### ISSUE TITLE
Import colors from file

### ISSUE THREAD

**Issue by XzanderX** [getflourish/Sketch-Style-Inventory#58]
I'm trying to import colors from an external file but it only creates a new small artboard and adds a text player that has the title from the first item. No swatches are created.

And yes, I've check the json file for errors :smile: 

I'm using Sketch Version 3.4.4 (17249)

**Comment by apertureless** [comment]
How do you trying to import them?
As far as I see, this plugin doesn't have an import function.

**Comment by apertureless** [comment]
Fixed this in the Pull Request.
