### ISSUE TITLE
Exporting colors doesn't export anything

### ISSUE THREAD

**Issue by coreyward** [getflourish/Sketch-Style-Inventory#61]
The code in `inventory.js` seems to imply a dialog should open to select a save location, but this does not happen. A message saying “Exporting to colors.json/colors.json” shows up and goes away, but no file is exported anywhere as far as I (or spotlight) can determine.

**Comment by apertureless** [comment]
Fixed in this pull request

https://github.com/getflourish/Sketch-Style-Inventory/pull/62

**Comment by ChrisARaymond** [comment]
I have a small Sketch file, with 2 pages. One page has rectangles with all my colors. I choose Generate Color Inventory, a page labeled color inventory is created, an alert saying Analyzing Colors appears, and then the only thing that shows is a blank background. Perhaps I am using the plugin wrong or not doing steps in the right order. I certainly never see anything like Swatches. Can anyone illuminate?

**Comment by sml-studio** [comment]
Same issue as ChrisARaymond : generate only an empty artboard on a new page.
And if "export" is checked, no dialogue appears to save a file.
Many tries with different sort of selections, etc.
Sketch 3.5.1

Thanks

**Comment by getflourish** [comment]
Updated the plugin to the new bundle format. Generate & Export should work again with the latest non-App Store versions.
