### ISSUE TITLE
symbol art board is not generated 

### ISSUE THREAD

**Issue by ShiranLia** [getflourish/Sketch-Style-Inventory#63]
only getting the text style and colors art board even though i select all the options
another thing is that the art board that im getting are overlap each other, and the text style art board is very small (dosent fit to the content - need to expand the art board manually)

**Comment by jacquelynchastain** [comment]
Having the same issue.

**Comment by getflourish** [comment]
Thanks for your report. I will update the plugin to work with the new plugin format.
