### ISSUE TITLE
RGBA for color inventory JSON export

### ISSUE THREAD

**Issue by adam-christiansen-design** [getflourish/Sketch-Style-Inventory#64]
The developers i'm working with / project i'm on would benefit greatly from having RGBA in the JSON export for color inventory.  If there is a way to make that happen, how?  If not, count this as a feature request.  Thanks!

**Comment by apertureless** [comment]
You can get the RGBA Tupel with MSColor.colorWithSVGString(hex_value). You could change it in the javascript for exporting.

**Comment by getflourish** [comment]
Thanks for your input. I will consider this when I update it for 3.5

**Comment by getflourish** [comment]
Changed to export/import RGBA
