### ISSUE TITLE
Incomplete generation of styles

### ISSUE THREAD

**Issue by jacquelynchastain** [getflourish/Sketch-Style-Inventory#65]
Love this plugin, wish it was functioning properly. Not sure if I have too many styles/symbols for it to work, but I get an incomplete generation. I don't get all of my symbols, type styles, or colors back... symbols seem to be there but you have to manually expand the container to see all of them. Please update?

**Comment by getflourish** [comment]
Thanks for your report. I will update the plugin to work with the new plugin format.
