### ISSUE TITLE
Just generate nothing

### ISSUE THREAD

**Issue by 105th** [getflourish/Sketch-Style-Inventory#66]
Ive have tried use this plugin first time and it did nothing generate.
I tried to reinstall plugin and sketch but nothing has changed.

This is my document:
![1453804297245](https://cloud.githubusercontent.com/assets/11395678/12578384/9741a1bc-c431-11e5-9631-ac8ee241620e.png)

It always generate the same file with empty colors directory.
![1453804407802](https://cloud.githubusercontent.com/assets/11395678/12578383/973fcc02-c431-11e5-9cd6-71649437a944.png)

But plugin looks like installed correctly
![1453804445400](https://cloud.githubusercontent.com/assets/11395678/12578382/973a2d2e-c431-11e5-8b91-c068030ee737.png)

**Comment by getflourish** [comment]
Thanks for your report. I need to update the plugin to work with the new plugin format.
