### ISSUE TITLE
Color Generation Artboard Empty

### ISSUE THREAD

**Issue by jacobswift** [getflourish/Sketch-Style-Inventory#67]
When I go to (Plugins > Sketch-style-inventory-master > Generate) and then I select (colors, text styles, symbols) the dialog for "analyzing colors" appears for a few seconds but only a blank artboard for "Color inventory" appears. No symbols or text style artboards appear.

When I follow the same procedure, but only select (text styles, symbols) it does generate text styles but not symbols.

When I follow the same procedure, but only select (text styles) it does generate text styles.

When I follow the same procedure, but only select (symbols) it does generate text symbols.

I updated my version of Sketch today to the latest version and that is when I noticed the issue.

**Comment by getflourish** [comment]
Thanks for your report. I need to update the plugin to work with the new plugin format.
