### ISSUE TITLE
Doesn't work with Sketch 3.5

### ISSUE THREAD

**Issue by webchun** [getflourish/Sketch-Style-Inventory#68]
:(

**Comment by jeckart3d** [comment]
I rely on this plugin a lot. A shame that 3.5 busts it. However, generating the COLORs is what causes the entire plugin to fail on 3.5. If you select text styles and symbols only, it still works. I don;t know if this is useful for you, but the color palettes are the easiest thing for me to maintain, collecting the symbols and font styles are most important to me.

Hopefully this helps you out.

**Comment by Geeza** [comment]
Thanks for the tip!

**Comment by ryanbeymer** [comment]
I was sad as well :( sometimes having a color swatch sheet is great for generating scss variables.

**Comment by meinmotion** [comment]
Me to, I'm using the plugin a lot and I love it. I hope that someone will update it soon

**Comment by ambersawaya** [comment]
Looks like the last 3 issues opened are all reporting the same problem (#68, #67, and #66). I love using the plugin and had the same issue in 3.5 today.

**Comment by mikeprecious** [comment]
I can confirm too, it seems to be the Color component that causes the plugin malfunction in Sketch 3.5.

**Comment by itsmekgaurav** [comment]
Please help in making this work. I wish I could help but bad I don't know coding.

**Comment by scorp84** [comment]
Yeah. Would be cool, if that could be fixed.

**Comment by getflourish** [comment]
Thanks for your reports. I will update the plugin to work with the new plugin format.
