### ISSUE TITLE
Generate doesn't work in Sketch 3.5.2

### ISSUE THREAD

**Issue by sboerrigter** [getflourish/Sketch-Style-Inventory#70]
Generating Style Inventories doesn't seem to work properly in the latest version of Sketch (3.5.2).
 
Whenever I try to generate the style inventory with all options (Colors, Text styles and Symbols) I only get an empty "Color Inventory" artboard, with no colors on it. I get the same result when I only select the "Colors" option:

![screen shot 2016-02-11 at 17 58 47](https://cloud.githubusercontent.com/assets/786875/12983372/5164ab84-d0e9-11e5-939d-ac43faaad2bd.png)

When I only select the "Text styles" option I get the text styles, but the arboards is too small:

![screen shot 2016-02-11 at 18 03 10](https://cloud.githubusercontent.com/assets/786875/12983485/be983bbc-d0e9-11e5-9ca2-e548a7fc2aad.png)

When I only select the "Symbols" option I get a blue artboard which is too small. All elements are outside of the canvas:

![screen shot 2016-02-11 at 18 04 47](https://cloud.githubusercontent.com/assets/786875/12983582/1bca69ea-d0ea-11e5-9ad6-fb8b5be90a3a.png)

I tried disabling all other plugins, but this doesn't help either.

**Comment by lokimuje** [comment]
https://github.com/getflourish/Sketch-Style-Inventory/pull/69/files

**Comment by fabiovella83** [comment]
thanks @lokimuje that fixes it!
the app is still quite unstable though...
@getflourish we wait for your update  :pray:

**Comment by AverySmith84** [comment]
Thanks for the fix @lokimuje

**Comment by hanjing7** [comment]
Thanks a lot, you are genius!

**Comment by getflourish** [comment]
Updated the plugin to the new bundle format. Generate & Export should work again with the latest non-App Store versions.
