### ISSUE TITLE
Generated symbol artboard does not contain symbols & no text styles generated.

### ISSUE THREAD

**Issue by iamlinkus** [getflourish/Sketch-Style-Inventory#73]
I'm getting strage results when trying to generate my style inventory. I have a few text styles and three symbols, but when I generate a style inventory, it gives me an inventory without any text styles and the symbols are strangely shifted out of the symbol artboard.

Text styles:

![screenshot 2016-03-02 13 55 08](https://cloud.githubusercontent.com/assets/16874184/13459813/ed9fac3e-e07e-11e5-95b1-7991d9474fa1.png)

Generated inventory:

![screenshot 2016-03-02 13 53 46](https://cloud.githubusercontent.com/assets/16874184/13459812/ed786b6a-e07e-11e5-9738-76344d9885ad.png)

**Comment by FoundDegree** [comment]
Oh that is exactly what I get with Sketch 3.6.1 ... so same issue like #74

**Comment by iamlinkus** [comment]
Yeah, @FoundDegree, seems it's the same issue. Been driving me nuts. I've been refreshing this repo for the last 6 days non stop..

**Comment by Bushwazi** [comment]
Same here. Sketch 3.6.1, no fonts, empty symbols and the fonts appear in a new window.

**Comment by ntdb** [comment]
I tried reverting to Sketch 3.6.0 as a as a temporary fix and experienced the same problems.

**Comment by KivyGogh** [comment]
Same here.

**Comment by ericajack** [comment]
Same here.

**Comment by getflourish** [comment]
Text Styles should work again. Sketch did some changes to how symbols work and I have to figure out how to fix this issue. For similar functionality, please refer to the new native Symbols sheet and for text styles and colors, see Craft by Invision: https://www.invisionapp.com/craft

I will look into the issue asap.

**Comment by getflourish** [comment]
Fixed in the latest version
