### ISSUE TITLE
Broken in Sketch 3.6.1?

### ISSUE THREAD

**Issue by FoundDegree** [getflourish/Sketch-Style-Inventory#74]
Hi there!

First of all, I love your plugin!! It was and is a game changer for me. But with the newly released version 3.6.1 of Sketch it seems to be broken as no text style is generated and it's not showing the proper Symbol names. A update of your plugin would save my life (again!).

Thanks for your hard work!
Harry

**Comment by Bushwazi** [comment]
+1

**Comment by ericajack** [comment]
+1

**Comment by Errortype520** [comment]
+1

**Comment by getflourish** [comment]
Text Styles should work again. Sketch did some changes to how symbols work and I have to figure out how to fix this issue. For similar functionality, please refer to the new native Symbols sheet and for text styles and colors, see Craft by Invision: https://www.invisionapp.com/craft

I will look into the issue asap.

**Comment by getflourish** [comment]
Fixed in the latest version
