### ISSUE TITLE
Not working in Sketch 3.7.0 

### ISSUE THREAD

**Issue by Augus** [getflourish/Sketch-Style-Inventory#75]

**Comment by FangXinhai** [comment]
I like your plugin, and I'm looking forward to the 3.7 version of the update, which will save us. thanks

@getflourish

**Comment by brunabites** [comment]
Styles not working. Symbols not working. Colors ok.

**Comment by getflourish** [comment]
Text Styles should work again. Sketch did some changes to how symbols work and I have to figure out how to fix this issue. For similar functionality, please refer to the new native Symbols sheet and for text styles and colors, see Craft by Invision: https://www.invisionapp.com/craft

I will look into the issue asap.

**Comment by getflourish** [comment]
Fixed in the latest version
