### ISSUE TITLE
Issue with Sketch 3.7.1

### ISSUE THREAD

**Issue by dezinerd** [getflourish/Sketch-Style-Inventory#76]
Hi, 

This plugin is awesome and very useful, however with the **last Sketch update** (3.7.1), the plugin's function gets borked when trying to perform the operation. 

Any news on when an update to the plugin will be available? 

Thank you!

**Comment by dantaylor** [comment]
Same here, nothing happens after choosing the "generate" menu item :(

**Comment by getflourish** [comment]
Fixed in the latest version
