### ISSUE TITLE
Sketch Version 3.8.3 (29802)

### ISSUE THREAD

**Issue by MAJ3STIC** [getflourish/Sketch-Style-Inventory#79]
Is there an update for Sketch Version 3.8.3 (29802)? The plugin stopped working before this patch even on a un-install/re-install.

**Comment by antonvh** [comment]
Same here. I'd like to make a color palette, but it turns up empty.

**Comment by benvan** [comment]
I have a pull request restoring color and text functionality. Unfortunately symbols are still broken.

https://github.com/getflourish/Sketch-Style-Inventory/pull/80

**Comment by antonvh** [comment]
Nice! Works fine.

**Comment by MAJ3STIC** [comment]
@benvan Thanks for the pull request. Will the color name be autogenerated in a future release?

**Comment by Isabellle** [comment]
Same here, I'm using the "Version 3.8.3 (29802)" and the only thing I get is "foo" and empty artboard

**Comment by melbayad** [comment]
Same here.

**Comment by Occur** [comment]
Same issue

**Comment by cnotte** [comment]
I'm having the same issues - empty art boards.  I used to use this all the time but now on 3.8.3 it's not working.

Will this be fixed?

**Comment by siscelica** [comment]
Same issue too :(

**Comment by getflourish** [comment]
Fixed
