### ISSUE TITLE
Sketch39 support

### ISSUE THREAD

**Issue by AquaHacker** [getflourish/Sketch-Style-Inventory#81]
Please Sketch39 support

**Comment by LastPixelBorn** [comment]
HI, after updating Sketch to version 39.1 (31720) plugin doesn't work anymore. After I press shortcut to generate styles (ctrl + ⌘ + ⌥ + I) I get empty page. Can you please do something about that, unfortunately I'm stuck in the middle of the important project. If it helps here are screenshots.

Step 1:
![image](https://cloud.githubusercontent.com/assets/18460472/17170185/3cb59de4-53eb-11e6-881f-b65f987fea8a.png)

Step 2:
![image](https://cloud.githubusercontent.com/assets/18460472/17170159/2997315a-53eb-11e6-9d9f-fb9279704e56.png)

**Comment by siscelica** [comment]
Having the same issue here.

**Comment by gnoren** [comment]
Also having this problem, so sad

**Comment by mattstvartak** [comment]
Having the same problem! Would love to see this resolved, plugin looks awesome.

**Comment by hhrrmnn** [comment]
Same here. "foo"'s the message I get (+ empty artboard)

**Comment by YurienJob** [comment]
Having the same issue here.

**Comment by jasondiameter** [comment]
Having the same issue as well. This was a big reason I got onto Sketch and now with this update Im looking down the barrel of a tonne of extra work...

When can we get a fix? please.

**Comment by siscelica** [comment]
One thing I do in the meantime is use Zeplin. It will gather all the screens and auto pull the styles and font sizes.
Still waiting on a fix for this.

**Comment by ximenacolla** [comment]
Same issue here --- getting "foo" message + empty artboard

**Comment by thebillettestate** [comment]
Same thing happening for me. Would really love for this to be fixed. Heavily relying on this plugin for an upcoming project. Thanks!

**Comment by nareeboy** [comment]
+1 Same thing is happening to me

**Comment by grzegorz-s** [comment]
+1

**Comment by brookenbrooklyn** [comment]
+1

**Comment by vanamco** [comment]
+1

**Comment by pablochux** [comment]
+1

**Comment by soulwasted** [comment]
+ 423

**Comment by soulwasted** [comment]
`+ 165`

**Comment by wacoom** [comment]
+1

**Comment by khoadpham** [comment]
+1

**Comment by sseen** [comment]
+1

**Comment by ahoebeke** [comment]
+1

**Comment by getflourish** [comment]
Fixed: Generate, Export, Selection.

@AquaHacker @LastPixelBorn @khoadpham @sseen @wacoom @soulwasted @pablochux @vanamco @brookenbrooklyn @grzegorz-s @nareeboy @thebillettestate @ximenacolla @siscelica @thebillettestate @jasondiameter @YurienJob @hhrrmnn @mattstvartak @gnoren

**Comment by soulwasted** [comment]
Crazy! It works!
Thanks! :)
