### ISSUE TITLE
Not generating inventory

### ISSUE THREAD

**Issue by sailtake5** [getflourish/Sketch-Style-Inventory#83]
When I follow the steps to generate an inventory, it doesn't seem to work.  It creates a new page titled "Style Inventory" but the page is empty.  Unless I'm missing something, the plugin seems to be broken with the latest version of Sketch.

**Comment by bhender** [comment]
I used to love this plugin but it no longer works. I have the same problem mentioned above.

**Comment by sailtake5** [comment]
Try Zeplin - saved my life.

**Comment by sailtake5** [comment]
https://zeplin.io/

**Comment by bhender** [comment]
yes I use zeplin. I found aCraft by Invision last night and it's a lifesaver. the plugin above is dead, use craft and zeplin.

**Comment by willimaese** [comment]
Same problem here

**Comment by swidnikk** [comment]
Same :-( this plugin was fantastic

**Comment by ahuk** [comment]
Although zeplin and sympli are somewhat different tools, Craft allows for the same features and has a bigger team behind it, and real cash ;)

**Comment by yisraelgrimes** [comment]
Found this plugin while looking for a Craft alternative. The only problem with craft is (from what I can tell) it inventories everything and not just selected layers.

**Comment by peterschmidler** [comment]
not working with 41 (as craft)

**Comment by ahoebeke** [comment]
+1

**Comment by caiocall** [comment]
Hi Guys! We are on the same road. I think not only this plugin should be fixed to work with newest versions of Sketch but also could allow us to say if we don't want some of the layers/styles to be added to the styleguide. Also the styleguide should have options that allow us to setup the main styles once as we want for example saying what is the H1, H2, and etc and not just guessing that by random order or sizes as it does. It's an amazing tool but I would love have it working and with some new features. Hope soon we can get it.

**Comment by getflourish** [comment]
Hi @caiocall thanks for your suggestions. I’m looking for ways to improve the overall functionality of this plugin. Feel free to create a new issues with your ideas so we can discuss them there.

**Comment by getflourish** [comment]
@all I’m currently updating the plugin and made a few commits that you can test already. Generation + Selection should work again.

**Comment by getflourish** [comment]
Fixed: Generate, Export, Selection.

@sailtake5 @bhender @willimaese @swidnikk @ahuk @ahoebeke @peterschmidler @yisraelgrimes @willimaese

**Comment by abinashmohanty** [comment]
Hey @getflourish it's the only plugin that used to support style inventory. But, It's stopped working in sketch 52. We really want to have it in order to create a inventory system. For symbols, I usually apply `symbol instance sheet`, now i'm stuck with my text/layer styles. Let's say if you have 40+ layer or text styles, it's way difficult to add them manually by going to text styles > parent > child > sub-child etc...

Please let me know. Also, I bet designers will definitely buy this plugin if you wanna develop this. In that case count me in. Cheers!
